package main

import "github.com/EgSundqvist/golangdemo0930/exercises"

func main() {
	//exercises.Exercise1()
	//exercises.Exercise2()
	//exercises.Exercise3()
	//exercises.Exercise4()
	//exercises.Exercise5()
	//exercises.Exercise6()
	//exercises.Exercise7()
	// exercises.Variables8()
	// exercises.Ifs1()
	// exercises.Ifs2()
	// exercises.Ifs3()
	//exercises.Ifs4()
	//exercises.Ifs5()
	// exercises.Ifs6()
	// exercises.Ifs7()
	// exercises.Ifs8()
	// exercises.Loops1()
	// exercises.Loops2()
	// exercises.Loops3()
	// exercises.Loops4()
	// exercises.Loops5()
	// exercises.Structures1()
	// exercises.Structures2()
	// exercises.Structures3()
	// exercises.Strings1()
	// exercises.Strings2()
	// exercises.Strings3()
	// exercises.Strings4()
	// exercises.Strings5()
	// exercises.Strings6()
	// exercises.Functions1()
	// exercises.Functions2()
	// exercises.Functions3()
	// exercises.Functions4()
	// exercises.Structs1()
	// exercises.Structs2()
	exercises.Structs3()
}
